In [1]:
import pandas as pd
df = pd.read_csv('onlinefraud.csv')
df = df.sample(6666)

In [2]:
df

,step,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud
6020448,466,PAYMENT,19225.02,C734517743,391.00,0.00,M131533932,0.00,0.00,0,0
312984,16,CASH_OUT,444222.35,C2107816073,12533.88,0.00,C1938841087,2904887.47,3241261.78,0,0
5573191,393,PAYMENT,10353.54,C1179616266,0.00,0.00,M1236300145,0.00,0.00,0,0
4417777,322,CASH_IN,259843.98,C747939809,2862750.27,3122594.25,C14555387,563740.41,303896.43,0,0
2696872,211,CASH_OUT,180917.03,C1811098197,0.00,0.00,C1292587944,1294039.22,1474956.25,0,0
...,...,...,...,...,...,...,...,...,...,...,...
3657637,275,TRANSFER,470693.07,C1150015783,0.00,0.00,C759194443,2132727.59,2603420.65,0,0
4232486,306,CASH_IN,44113.10,C2065141292,15043.00,59156.10,C439010305,0.00,0.00,0,0
4170551,304,CASH_OUT,233910.72,C1210440079,56226.00,0.00,C1014137311,0.00,233910.72,0,0
4038677,299,CASH_IN,193021.08,C220007627,10637881.98,10830903.06,C649092770,796978.23,603957.15,0,0
2124022,183,PAYMENT,4649.80,C1261882167,0.00,0.00,M1186982934,0.00,0.00,0,0

In [3]:
# code=utf-8
import pandas as pd

# 打开文件
data = pd.read_csv('onlinefraud.csv')

# 每个excel保存3万行，那么530000+数据需要18个.csv文档保存
save_data = data.iloc[1 : 30000]
file_name = r'online_fraud.csv'  # 保存文件路径以及文件名称
save_data.to_csv(file_name, index=False)  # 保存格式为.csv，如果是xlsx则修改为save_data.to_excel